## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: chembl_webresource_client in c:\program files\python39\lib\site-packages (0.10.7)
Requirement already satisfied: requests-cache~=0.7.0 in c:\program files\python39\lib\site-packages (from chembl_webresource_client) (0.7.5)
Requirement already satisfied: requests>=2.18.4 in c:\program files\python39\lib\site-packages (from chembl_webresource_client) (2.26.0)
Requirement already satisfied: easydict in c:\program files\python39\lib\site-packages (from chembl_webresource_client) (1.9)
Requirement already satisfied: urllib3 in c:\program files\python39\lib\site-packages (from chembl_webresource_client) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\program files\python39\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python39\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (2021.5.30)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python39\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.2)
Requirement already satisfied: pyyaml>=5.4 in c:\program files\python39\lib\site-packages (from requests-cache~=0.7.0->chembl_webresource_client) (5.4.1)
Requirement already satisfied: itsdangerous>=2.0.1 in c:\program files\python39\lib\site-packages (from requests-cache~=0.7.0->chembl_webresource_client) (2.0.1)
Requirement already satisfied: attrs<22.0,>=21.2 in c:\program files\python39\lib\site-packages (from requests-cache~=0.7.0->chembl_webresource_client) (21.2.0)
Requirement already satisfied: url-normalize<2.0,>=1.4 in c:\program files\python39\lib\site-packages (from requests-cache~=0.7.0->chembl_webresource_client) (1.4.3)
Requirement already satisfied: six in c:\program files\python39\lib\site-packages (from url-normalize<2.0,>=1.4->requests-cache~=0.7.0->chembl_webresource_client) (1.16.0)

## **Importing libraries**

In [2]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for TLR2**

In [3]:
# Target search for TLR2
target = new_client.target
target_query = target.search('TLR2')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,"[{'xref_id': 'Q9QUN7', 'xref_name': None, 'xre...",Mus musculus,Toll-like receptor 2,16.0,False,CHEMBL1075106,"[{'accession': 'Q9QUN7', 'component_descriptio...",SINGLE PROTEIN,10090
1,[],Mus musculus,TLR2/TLR6,16.0,False,CHEMBL3137289,"[{'accession': 'Q9QUN7', 'component_descriptio...",PROTEIN COMPLEX,10090
2,[],Homo sapiens,TLR2/TLR6,16.0,False,CHEMBL3301399,"[{'accession': 'O60603', 'component_descriptio...",PROTEIN COMPLEX,9606
3,"[{'xref_id': 'O60603', 'xref_name': None, 'xre...",Homo sapiens,Toll-like receptor 2,13.0,False,CHEMBL4163,"[{'accession': 'O60603', 'component_descriptio...",SINGLE PROTEIN,9606
4,[],Mus musculus,Toll-like receptor 1/2,12.0,False,CHEMBL3885644,"[{'accession': 'Q9QUN7', 'component_descriptio...",PROTEIN COMPLEX,10090
5,[],Homo sapiens,Toll-like receptor 1/2,10.0,False,CHEMBL3885643,"[{'accession': 'O60603', 'component_descriptio...",PROTEIN COMPLEX,9606

## **Select and retrieve bioactivity data for *TLR2* (fourth entry)**

We will assign the fourth entry (which corresponds to the target protein, *TLR2*) to the ***selected_target*** variable

In [4]:
selected_target = targets.target_chembl_id[3]
selected_target

'CHEMBL4163'

Here, we will retrieve only bioactivity data for *TLR2* (CHEMBL4163) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [5]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [6]:
df = pd.DataFrame.from_dict(res)

In [7]:
df

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,1660296,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,3.07
1,None,1660298,[],CHEMBL853288,Antagonistic activity at TLR in human PBMC,F,None,None,BAO_0000190,BAO_0000019,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.6
2,None,1660299,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.9
3,None,1660300,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.95
4,None,1660301,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,5.2
5,None,1660302,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.25
6,None,1660303,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,2.15
7,None,1660304,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,22.0
8,None,1660305,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,6.9
9,None,1660306,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,6.46
10,None,1698301,[],CHEMBL867222,Inhibition of TLR2 agonist Pam3Cys-Ser-(Lys)4-...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,5.0
11,None,1698302,[],CHEMBL867222,Inhibition of TLR2 agonist Pam3Cys-Ser-(Lys)4-...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,5.0
12,None,2468831,[],CHEMBL989789,Antagonist activity at human TLR2 expressed in...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.23
13,None,2468832,[],CHEMBL989789,Antagonist activity at human TLR2 expressed in...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.9
14,None,2468833,[],CHEMBL989789,Antagonist activity at human TLR2 expressed in...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.24
15,None,2468834,[],CHEMBL989789,Antagonist activity at human TLR2 expressed in...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.46
16,None,2468835,[],CHEMBL990600,Inhibition of TLR2-mediated IL8 secretion in h...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,5.0
17,None,3257498,[],CHEMBL1108919,Inhibition of human TLR2 expressed in HEK-Blue...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,nM,UO_0000065,None,48.0
18,None,3257499,[],CHEMBL1108919,Inhibition of human TLR2 expressed in HEK-Blue...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.2
19,None,18582329,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,0.5501,0.4263
20,None,18582330,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,7.519
21,None,18582331,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,6.427
22,None,18582332,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,4.363
23,None,18582333,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,3.938
24,None,18582334,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.682
25,None,18582335,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.962
26,None,18582336,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,4.651
27,None,18582337,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,4.755
28,None,18582338,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,3.373
29,None,19095246,[],CHEMBL4367446,Inhibition of TLR2 in HEK293 cells assessed as...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,10.0
30,None,20678685,[],CHEMBL4622263,Antagonist activity at TLR2 in human PBMC asse...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,6.5

In [8]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [9]:
df.to_csv('bioactivity_data.csv', index=False)

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [10]:
! bioactivity_data.csv

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [11]:
df2 = df[df.standard_value.notna()]
df2

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,1660296,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,3.07
1,None,1660298,[],CHEMBL853288,Antagonistic activity at TLR in human PBMC,F,None,None,BAO_0000190,BAO_0000019,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.6
2,None,1660299,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.9
3,None,1660300,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.95
4,None,1660301,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,5.2
5,None,1660302,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.25
6,None,1660303,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,2.15
7,None,1660304,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,22.0
8,None,1660305,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,6.9
9,None,1660306,[],CHEMBL860291,Antagonistic potency at TLR2 expressed in HEK2...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,6.46
10,None,1698301,[],CHEMBL867222,Inhibition of TLR2 agonist Pam3Cys-Ser-(Lys)4-...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,5.0
11,None,1698302,[],CHEMBL867222,Inhibition of TLR2 agonist Pam3Cys-Ser-(Lys)4-...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,5.0
12,None,2468831,[],CHEMBL989789,Antagonist activity at human TLR2 expressed in...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.23
13,None,2468832,[],CHEMBL989789,Antagonist activity at human TLR2 expressed in...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.9
14,None,2468833,[],CHEMBL989789,Antagonist activity at human TLR2 expressed in...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.24
15,None,2468834,[],CHEMBL989789,Antagonist activity at human TLR2 expressed in...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,0.46
16,None,2468835,[],CHEMBL990600,Inhibition of TLR2-mediated IL8 secretion in h...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,5.0
17,None,3257498,[],CHEMBL1108919,Inhibition of human TLR2 expressed in HEK-Blue...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,nM,UO_0000065,None,48.0
18,None,3257499,[],CHEMBL1108919,Inhibition of human TLR2 expressed in HEK-Blue...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.2
19,None,18582329,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,0.5501,0.4263
20,None,18582330,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,7.519
21,None,18582331,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,6.427
22,None,18582332,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,4.363
23,None,18582333,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,3.938
24,None,18582334,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.682
25,None,18582335,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,1.962
26,None,18582336,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,4.651
27,None,18582337,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,4.755
28,None,18582338,[],CHEMBL4222924,Inhibition of biotin labelled Pam2CSK4 binding...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,3.373
29,None,19095246,[],CHEMBL4367446,Inhibition of TLR2 in HEK293 cells assessed as...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,10.0
30,None,20678685,[],CHEMBL4622263,Antagonist activity at TLR2 in human PBMC asse...,B,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Toll-like receptor 2,9606,None,None,IC50,uM,UO_0000065,None,6.5

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active or inactive**
The bioactivity data is in the IC50 unit. Compounds having values of less than 3000 nM will be considered to be **active** while those greater than 3,000 nM will be considered to be **inactive**.

In [12]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 3000:
    bioactivity_class.append("inactive")
  elif float(i) <= 3000:
    bioactivity_class.append("active")

### **Iterate the *molecule_chembl_id* to a list**

In [13]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [14]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [15]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [16]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [17]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL382272,CCCCCCCCCCCCCC(=O)N[C@H](COCC[C@@H](CCCCCCC)OC...,inactive,3070.0
1,CHEMBL382272,CCCCCCCCCCCCCC(=O)N[C@H](COCC[C@@H](CCCCCCC)OC...,active,1600.0
2,CHEMBL383597,CCCCCCCCCCCCCC(=O)N[C@@H](COP(=O)(O)OCCNC(=O)C...,active,900.0
3,CHEMBL372577,CCCCCCCCCCCCCC(=O)N[C@@H](COP(=O)(O)OCCNC(=O)C...,active,950.0
4,CHEMBL380585,CCCCCCCCCCCCCC(=O)N[C@H](COCC[C@@H](CCCCCCC)NC...,inactive,5200.0
5,CHEMBL190383,CCCCCCCCCCCCCC(=O)O[C@H](COCC[C@@H](CCCCCCC)OC...,active,1250.0
6,CHEMBL200206,CCCCCCCCCCCCCC(=O)N[C@H](COCC[C@@H](CCCCCCC)OC...,active,2150.0
7,CHEMBL200140,CCCCCCCCCCCCCC(=O)N[C@@H](COCC[C@@H](CCCCCCC)O...,inactive,22000.0
8,CHEMBL200667,CCCCCCCCCCCCCC(=O)N[C@@H](COCC[C@H](CCCCCCC)OC...,inactive,6900.0
9,CHEMBL200398,CCCCCCCCCCCCCC(=O)N[C@H](COCC[C@H](CCCCCCC)OC(...,inactive,6460.0
10,CHEMBL111077,CCCCCCCCCCCCCC(=O)O,inactive,5000.0
11,CHEMBL82293,CCCCCCCCCCCCCCCC(=O)O,inactive,5000.0
12,CHEMBL490908,CCCCCCCCCCCCCCCC(=O)N[C@@H](COP(=O)(O)OCCNC(=O...,active,230.0
13,CHEMBL446794,CCCCCCCCCCCCCC(=O)N[C@@H](COP(=O)(O)OCCNC(=O)[...,active,900.0
14,CHEMBL448621,CCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](COP(=O)(O)OCCN...,active,240.0
15,CHEMBL473383,CCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](COP(=O)(O)OCCN...,active,460.0
16,CHEMBL414311,CCCCCCCCCCCCCC(=O)N[C@@H](CSC[C@H](NC(=O)CCCCC...,inactive,5000.0
17,CHEMBL1092429,CCCCCCCCCCCCCCCC(=O)N[C@H](COC(=O)CCCCCCCCCCCC...,active,48.0
18,CHEMBL1092428,CCCCCCCCCCCCCCCC(=O)OC[C@H](CSCCNC(=O)[C@H](N)...,active,1200.0
19,CHEMBL2179400,CCCCCCCCCCCCCCCC(=O)OC[C@H](CSC[C@H](N)C(=O)N[...,active,426.3
20,CHEMBL4227041,CCCCCCCCCCCCCCCC(=O)O[C@H](COC(=O)CCCCCCCCNC(=...,inactive,7519.0
21,CHEMBL4229084,CCCCCCCCCCCCCCCC(=O)O[C@H](COC(=O)CCCCCCCCCNC(...,inactive,6427.0
22,CHEMBL4226658,CCCCCCCCCCCCCCCC(=O)O[C@H](COC(=O)CCCCCCCCCCNC...,inactive,4363.0
23,CHEMBL4226518,CCCCCCCCCCCCCCCC(=O)O[C@H](COC(=O)CCCCCCCCCCCN...,inactive,3938.0
24,CHEMBL4225423,CCCCCCCCCCCCCCCC(=O)OC[C@H](CSC[C@H](N)C(=O)N[...,active,1682.0
25,CHEMBL4226256,CCCCCCCCCCCCCCCC(=O)OC[C@H](CSC[C@H](N)C(=O)N[...,active,1962.0
26,CHEMBL4225148,CCCCCCCCCCCCCCCC(=O)OC[C@H](CSC[C@H](N)C(=O)N[...,inactive,4651.0
27,CHEMBL4227905,CCCCCCCCCCCCCCCC(=O)OC[C@H](CSC[C@H](N)C(=O)N[...,inactive,4755.0
28,CHEMBL4224884,CCCCCCCCCCCCCCCC(=O)OC[C@H](CSC[C@H](N)C(=O)N[...,inactive,3373.0
29,CHEMBL4514780,CC(C)(C)S(=O)(=O)c1cc2c(Nc3ccc4scnc4c3)ncnc2cc...,inactive,10000.0
30,CHEMBL4641633,O=c1ccc(-c2cc(C(F)(F)F)c3nn([C@H]4CCNC[C@@H]4F...,inactive,6500.0

In [18]:
df3.to_excel("TLR2_data.xlsx")

In [19]:
df3.to_csv('Preprocessed_bioactivity_data.csv', index=False)

In [20]:
! Preprocessed_bioactivity_data.csv

                       ---In this part, data is collected and curated according to the need.---